name: overlay_popup_dialog
description: Easily position custom dialogs relative to any widget. Easy to use for every platform.
version: 2.0.1
homepage: https://github.com/metekaganmusaak/overlay_popup_dialog

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

screenshots:
  - description: "Package Logo"
    path: assets/logo.png
